google.credentials.path=google-credentials.json
twilio.account.sid=YOUR_ACCOUNT_SID
twilio.auth.token=YOUR_AUTH_TOKEN
twilio.phone.number=YOUR_TWILIO_PHONE_NUMBER
otp.expiration.minutes=5
mail.host=smtp.gmail.com
mail.port=587
mail.username=nekaiesadem7@gmail.com
mail.password=YOUR_GMAIL_APP_PASSWORD
mail.from=nekaiesadem7@gmail.com
mythoria.mail.host=sandbox.smtp.mailtrap.io
mythoria.mail.port=587
mythoria.mail.username=YOUR_MYTHORIA_MAIL_USERNAME
mythoria.mail.password=YOUR_MYTHORIA_MAIL_PASSWORD
mythoria.mail.from=no-reply@mythoria.local
