google.credentials.path=C:/Users/dell/Downloads/sonic-potion-494619-c0-106b424c6f45.json
twilio.account.sid=YOUR_ACCOUNT_SID
twilio.auth.token=YOUR_AUTH_TOKEN
twilio.phone.number=YOUR_TWILIO_PHONE_NUMBER
otp.expiration.minutes=5
